--CONTIENE LOS POSIBLES ESTADOS EN LOS QUE PUEDE ESTAR UN MENSAJE
CREATE TABLE "SMS_ESTATUS" (

"ID" NUMBER(10) NOT NULL,

"DESCRIPCION" NVARCHAR2(255) NULL,

"CODIGO_PROVEEDOR" NVARCHAR2(20) NULL,

"ID_PROVEEDOR" NUMBER(10) NULL,

PRIMARY KEY ("ID") 

);

--CONTIENE LOS ALIADOS COMERCIALES O SOCIOS DE NEGOCIO, TALES COMO CLINICAS, HOSPITALES, ETC
CREATE TABLE "AFILIADOS" (

"ID" NUMBER(10) NOT NULL,

"NOMBRE" NVARCHAR2(50) NULL,

"TELEFONO" NVARCHAR2(14) NULL,

"DIRECCION" NVARCHAR2(300) NULL,

"EMAIL" NVARCHAR2(50) NULL,

PRIMARY KEY ("ID") 

);

--CONTIENE LA CLASIFICACION DE LOS MENSAJES QUE PUEDE SE PUEDEN ENVIAR
CREATE TABLE "SMS_TIPOS_MENSAJES" (

"ID" NUMBER(10) NOT NULL,

"CONTENIDO" NVARCHAR2(255) NULL,

"ID_AFILIADO" NUMBER(10) NULL,

PRIMARY KEY ("ID") 

);

--CONTIENE LOS DISTINTOS PROVEEDORES DE SERVICIOS
CREATE TABLE "PROVEEDORES" (

"ID" NUMBER(10) NOT NULL,

"NOMBRE" NVARCHAR2(255) NULL,

"RIF" NVARCHAR2(10) NULL,

"TELEFONO" NVARCHAR2(14) NULL,

"DIRECCION" NVARCHAR2(500) NULL,

"EMAIL" NVARCHAR2(50) NULL,

PRIMARY KEY ("ID") 

);


--CONTIENE LOS MENSAJES A ENVIAR, ENVIADO Y FALLIDOS O POR REENVIAR
CREATE TABLE "SMS_MENSAJES" (

"ID" NUMBER(10) NOT NULL,

"FECHA" DATE NULL,

"ID_TIPO_MENSAJE" NUMBER(10) NULL,

"ID_CLIENTE" NUMBER(10) NULL,

PRIMARY KEY ("ID") 

);


-- CONTIENE EL NUMERO DE LOTE, PARA ENVIOS MASIVOS
CREATE TABLE "SMS_LOTES" (

"ID" NUMBER(10) NOT NULL,

"FECHA" DATE NULL,

PRIMARY KEY ("ID") 

);


-- CONTIENE LOS DATOS DE LOS CLIENTES A LOS CUALES SE LE ENVIARAN LOS MENSAJES
CREATE TABLE "CLIENTES" (

"ID" NUMBER(10) NOT NULL,

"CEDULA" NUMBER(10) NULL,

"NOMBRE" NVARCHAR2(50) NULL,

"CELULAR" NVARCHAR2(14) NULL,

"DIRECCION" NVARCHAR2(300) NULL,

"EMAIL" NVARCHAR2(50) NULL,

PRIMARY KEY ("ID") 

);


-- CONTIENE LOS POSIBLES ESTADOS DE UN MENSAJE
CREATE TABLE "SMS_ESTATUS_MENSAJES" (

"ID" NUMBER(10) NULL,

"ID_MENSAJE" NUMBER(10) NULL,

"ID_ESTATUS" NUMBER(10) NULL,

"FECHA" DATE NULL,

"LOTE" NUMBER(10) NULL,

PRIMARY KEY ("ID") 
);


ALTER TABLE "SMS_ESTATUS" ADD CONSTRAINT "fk_SMS_ESTATUS_PROVEEDOR" FOREIGN KEY ("ID_PROVEEDOR") REFERENCES "PROVEEDORES" ("ID");

ALTER TABLE "SMS_TIPOS_MENSAJES" ADD CONSTRAINT "fk_SMS_TIPOS_MENS_AFILIADOS" FOREIGN KEY ("ID_AFILIADO") REFERENCES "AFILIADOS" ("ID");

ALTER TABLE "SMS_MENSAJES" ADD CONSTRAINT "fk_SMS_MENSAJES_TIPOS_MENSAJES" FOREIGN KEY ("ID_TIPO_MENSAJE") REFERENCES "SMS_TIPOS_MENSAJES" ("ID");

ALTER TABLE "SMS_MENSAJES" ADD CONSTRAINT "fk_SMS_MENSAJES_CLIENTES" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES" ("ID");

ALTER TABLE "SMS_ESTATUS_MENSAJES" ADD CONSTRAINT "fk_SMS_ESTATUS_MENSAJES_LOTES" FOREIGN KEY ("LOTE") REFERENCES "SMS_LOTES" ("ID");

ALTER TABLE "SMS_ESTATUS_MENSAJES" ADD CONSTRAINT "fk_SMS_EST_MENS_SMS_ESTATUS" FOREIGN KEY ("ID_ESTATUS") REFERENCES "SMS_ESTATUS" ("ID");

--SECUENCIAS
CREATE SEQUENCE SEC_ESTATUS_MENSAJES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE SEC_LOTES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE SEC_TIPOS_MENSAJES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE SEC_MENSAJES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

CREATE SEQUENCE SEC_CLIENTES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
CREATE SEQUENCE SEC_PROVEEDORES
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE SEC_AFILIADOS
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
 
CREATE SEQUENCE SEC_ESTATUS
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
 
--TRIGGERS
CREATE OR REPLACE TRIGGER TRI_MENSAJES
BEFORE INSERT ON SMS_MENSAJES REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_ESTATUS_MENSAJES
BEFORE INSERT ON SMS_ESTATUS_MENSAJES REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_TIPOS_MENSAJES
BEFORE INSERT ON SMS_TIPOS_MENSAJES
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_CLIENTES
BEFORE INSERT ON CLIENTES REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_PROVEEDORES
BEFORE INSERT ON PROVEEDORES REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_AFLIADOS
BEFORE INSERT ON AFILIADOS REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;

CREATE OR REPLACE TRIGGER TRI_ESTATUS
BEFORE INSERT ON SMS_ESTATUS REFERENCING NEW AS NEW FOR EACH ROW
DECLARE vSec NUMBER := 0;
BEGIN

 IF (:OLD.id is null) THEN
  SELECT SEC_MENSAJES.NEXTVAL INTO vSec FROM DUAL;
  :NEW.id := vSec;
 END IF;

END;
--COMENTARIOS

COMMENT ON COLUMN SMS_ESTATUS.ID IS 'Identificador del estatus del mensaje';
COMMENT ON COLUMN SMS_ESTATUS.DESCRIPCION IS 'Texto del mensaje a enviar';
COMMENT ON COLUMN SMS_ESTATUS.CODIGO_PROVEEDOR IS 'Codigo que asigna el proveedor de servicio al estado del mensaje';
COMMENT ON COLUMN SMS_ESTATUS.ID_PROVEEDOR IS 'Identificador del proveedor de servicios';
COMMENT ON COLUMN AFILIADOS.ID IS 'Identificador del socio o aliado comercial';
COMMENT ON COLUMN AFILIADOS.NOMBRE IS 'Nombre del socio o aliado comercial';
COMMENT ON COLUMN AFILIADOS.TELEFONO IS 'Telefono del socio o aliado comercial';
COMMENT ON COLUMN AFILIADOS.DIRECCION IS 'Direccion del socio o aliado comercial';
COMMENT ON COLUMN AFILIADOS.EMAIL IS 'Correlo electronico del socio o aliado comercial';
COMMENT ON COLUMN PROVEEDORES.ID IS 'Identificador del proveedor de servicios';
COMMENT ON COLUMN PROVEEDORES.NOMBRE IS 'Nombre del proveedor de servicios';
COMMENT ON COLUMN PROVEEDORES.RIF IS 'Rif del proveedor de servicios';
COMMENT ON COLUMN PROVEEDORES.TELEFONO IS 'Telefono del proveedor de servicios';
COMMENT ON COLUMN PROVEEDORES.DIRECCION IS 'Direccion del proveedor de servicios';
COMMENT ON COLUMN PROVEEDORES.EMAIL IS 'Correlo electronico del proveedor de servicios';
COMMENT ON COLUMN CLIENTES.ID IS 'Identificador del cliente';
COMMENT ON COLUMN CLIENTES.CEDULA IS 'Cedula del cliente';
COMMENT ON COLUMN CLIENTES.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTES.CELULAR IS 'Telefono celular del cliente';
COMMENT ON COLUMN CLIENTES.DIRECCION IS 'Direccion del cliente';
COMMENT ON COLUMN CLIENTES.EMAIL IS 'Correlo electronico del cliente';
COMMENT ON COLUMN SMS_TIPOS_MENSAJES.ID IS 'Identificador del mensaje';
COMMENT ON COLUMN SMS_TIPOS_MENSAJES.CONTENIDO IS 'Texto del mensaje';
COMMENT ON COLUMN SMS_TIPOS_MENSAJES.ID_AFILIADO IS 'Identificador del aliado comercial al cual pertenece el mensaje';
COMMENT ON COLUMN SMS_MENSAJES.ID IS 'Identificador del mensaje que sera enviado';
COMMENT ON COLUMN SMS_MENSAJES.FECHA IS 'Fecha de envio del mensaje';
COMMENT ON COLUMN SMS_MENSAJES.ID_TIPO_MENSAJE IS 'Identificador del tipo de mensaje que sera enviado';
COMMENT ON COLUMN SMS_MENSAJES.ID_CLIENTE IS 'Identificador del cliente al cual se le enviara el mensaje';
COMMENT ON COLUMN SMS_LOTES.ID IS 'Identificador del lote';
COMMENT ON COLUMN SMS_LOTES.FECHA IS 'Fecha de envio del lote';
COMMENT ON COLUMN SMS_ESTATUS_MENSAJES.ID IS 'Numero de secuencia de los  estados del mensaje';
COMMENT ON COLUMN SMS_ESTATUS_MENSAJES.ID_MENSAJE IS 'Identificador del mensaje enviado';
COMMENT ON COLUMN SMS_ESTATUS_MENSAJES.ID_ESTATUS IS 'Identificador del estatus del mensaje';
COMMENT ON COLUMN SMS_ESTATUS_MENSAJES.FECHA IS 'Fecha de envio del mensaje';
COMMENT ON COLUMN SMS_ESTATUS_MENSAJES.LOTE IS 'Numero de lote utilizado para envios masivo';
/