--ELIMINADO LAS TABLAS EXISTENTES

ALTER TABLE CS_EX_ESTATUS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_ESTATUS CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_CENTROS_SALUD
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_CENTROS_SALUD CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_TIPOS_MENSAJES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_TIPOS_MENSAJES CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_PROVEEDORES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_PROVEEDORES CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_MENSAJES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_MENSAJES CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_LOTES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_LOTES CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_CLIENTES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_CLIENTES CASCADE CONSTRAINTS;

ALTER TABLE CS_EX_ESTATUS_MENSAJES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_ESTATUS_MENSAJES CASCADE CONSTRAINTS;


ALTER TABLE CS_EX_PARAMETROS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_PARAMETROS CASCADE CONSTRAINTS;


ALTER TABLE CS_EX_PLANTILLAS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_PLANTILLAS CASCADE CONSTRAINTS;


ALTER TABLE CS_EX_CENTROS_CLIENTES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_CENTROS_CLIENTES CASCADE CONSTRAINTS;


ALTER TABLE CS_EX_UNIDAD
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_UNIDAD CASCADE CONSTRAINTS;


ALTER TABLE CS_EX_PARAM_TIPO_MENSAJE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_EX_PARAM_TIPO_MENSAJE CASCADE CONSTRAINTS;

--ELIMINADO SECUENCIAS
DROP SEQUENCE CS_EX_SEC_ESTATUS;
DROP SEQUENCE CS_EX_SEC_CENTROS_SALUD;
DROP SEQUENCE CS_EX_SEC_TIPOS_MENSAJES;
DROP SEQUENCE CS_EX_SEC_PROVEEDORES;
DROP SEQUENCE CS_EX_SEC_MENSAJES;
DROP SEQUENCE CS_EX_SEC_LOTES;
DROP SEQUENCE CS_EX_SEC_CLIENTES;
DROP SEQUENCE CS_EX_SEC_ESTATUS_MENSAJES;
DROP SEQUENCE CS_EX_SEC_PARAMETROS;
DROP SEQUENCE CS_EX_SEC_PLANTILLAS;
DROP SEQUENCE CS_EX_SEC_UNIDAD;

 /